version: '3.1'

services:

  db:
    build: ./db
    container_name: mariadb_bs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hofesa123/
    ports:
    - 3306:3306

  adminer:
    build: ./adminer
    container_name: adminer_bs
    restart: always
    ports:
    - 6080:8080

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin_bs
    restart: always
    ports:
    - 7080:80