version: '3.1'

services:

  db:
    build: ./db
    container_name: postgres_bs
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hofesa123/
    ports:
    - 5433:5432

  adminer:
    build: ./adminer
    container_name: adminer_bs
    restart: always
    ports:
    - 6080:8080
